Feature/maze game hieu
gdsc-hcmut/game-be pull request #65
Opened 2023-08-17 12:04 UTC by quochieu586

add new models: 
+ sessionMaze
+ roundMaze

new APIs: 
+ start session
+ start round

2023-08-17 16:02 UTC, tomgermanyyyy commented on src/models/round_maze_game.model.ts
> +export type RoundState = 'inProgress' | 'Win' | 'Lose';
InProgress , enum

2023-08-17 16:02 UTC, tomgermanyyyy commented on src/models/round_maze_game.model.ts
> +export type RoundState = 'inProgress' | 'Win' | 'Lose';
Status

2023-08-18 15:24 UTC, lygioian commented
:) coi lại cách đặt tên branch nhe @quochieu586, a mà thấy đặt v nữa là a close PR nha

2023-08-18 15:37 UTC, lygioian requested changes

2023-08-18 15:37 UTC, lygioian commented on src/controllers/maze.controller.ts
> +        this.router.post('/maze/singlemove/:id', this.singleMove.bind(this));
coi lại cách đặt tên 
tại sao createNewMap lại /round/:id ? mà lại còn method là get ? 
singleMove :)) là gì mà lại/maze/singlemove/:id ??

2023-08-18 15:37 UTC, lygioian commented on src/controllers/maze.controller.ts
> +            const newMap = await this.mazeService.createMap(id);
tại sao tạo map mới chỉ truyền id ?

2023-08-18 15:37 UTC, lygioian commented on src/models/maze_game_session.model.ts
> +export type MazeGameSessionDocument = Document & {
MazeGameSession phải lưu lại MazeGameId để ref lại

2023-08-18 15:39 UTC, lygioian requested changes

2023-08-18 15:39 UTC, lygioian commented on src/services/maze.service.ts
> +            nextPosition = character.position + session.size.width;
ở lên lấy width height ra rồi sao ở đây lại dùng session.size.width

2023-08-18 15:54 UTC, tomgermanyyyy requested changes

2023-08-18 15:54 UTC, tomgermanyyyy commented on src/constant/maze/map/cellClass.ts
> +            case 'path':
enum

2023-08-18 15:54 UTC, tomgermanyyyy commented on src/constant/maze/map/cellClass.ts
> +    abstract handler(character: Character): boolean; // Check whether the move step can be done.
handle

2023-08-18 15:54 UTC, tomgermanyyyy commented on src/constant/maze/map/index.ts
> +// import mongoose from 'mongoose';
remove comment

2023-08-18 15:54 UTC, tomgermanyyyy commented on src/constant/maze/map/index.ts
> +// ];
remove comment

2023-08-18 15:54 UTC, tomgermanyyyy commented on src/controllers/maze.controller.ts
> +        this.router.post('/maze/singlemove/:id', this.singleMove.bind(this));
single-move
/api

2023-08-18 15:54 UTC, tomgermanyyyy commented on src/controllers/maze.controller.ts
> +    async singleMove(req: Request, res: Response) {
submitSingleMove

2023-08-18 15:54 UTC, tomgermanyyyy commented on src/controllers/maze.controller.ts
> +            switch (req.query.move) {
dùng payload

2023-08-18 15:54 UTC, tomgermanyyyy commented on src/controllers/maze.controller.ts
> +                case 'w':
a, s, d, w -> enum

2023-08-18 15:54 UTC, tomgermanyyyy commented on src/models/maze_game.model.ts
> +// export enum CellType {
enum CellType {
Path = 'path'
}

2023-08-18 15:54 UTC, tomgermanyyyy commented on src/services/maze.service.ts
> +type Direction = 'up' | 'down' | 'left' | 'right';
enum

2023-08-18 15:54 UTC, tomgermanyyyy commented on src/services/maze.service.ts
> +    }
nên là 1 hàm move thôi

2023-08-19 05:09 UTC, quochieu586 commented on src/constant/maze/map/cellClass.ts
> +    isValid: boolean;
Dạ rồi, chỗ này e chỉnh thành 1 cái class luôn rồi a

2023-08-19 05:09 UTC, quochieu586 commented on src/constant/maze/map/cellClass.ts
> +    abstract handler(character: Character): boolean; // Check whether the move step can be done.
Dạ ròi

2023-08-19 05:10 UTC, quochieu586 commented on src/constant/maze/map/cellClass.ts
> +            case 'path':
Dạ ròi

2023-08-19 05:10 UTC, quochieu586 commented on src/constant/maze/map/index.ts
> +// import mongoose from 'mongoose';
Dạ ròi

2023-08-19 05:10 UTC, quochieu586 commented on src/constant/maze/map/index.ts
> +// ];
Dạ ròi

2023-08-19 05:13 UTC, quochieu586 commented on src/controllers/maze.controller.ts
> +        this.router.post('/maze/singlemove/:id', this.singleMove.bind(this));
Dạ e chỉnh ròi

2023-08-19 05:13 UTC, quochieu586 commented on src/controllers/maze.controller.ts
> +        this.router.post('/maze/singlemove/:id', this.singleMove.bind(this));
Dạ ròi

2023-08-19 05:14 UTC, quochieu586 commented on src/controllers/maze.controller.ts
> +            const newMap = await this.mazeService.createMap(id);
Dạ chỗ này e chỉnh ròi. Mục định của cái controller này để tạo dữ liệu cho db thay vì mình tạo trực tiếp trên kia á anh.

2023-08-19 05:14 UTC, quochieu586 commented on src/controllers/maze.controller.ts
> +            const userId = new Types.ObjectId(req.tokenMeta.userId);
Dạ khúc này e có check coi cái session của user có tồn tại ko, nếu có thì có đang InProgress ko á anh

2023-08-19 05:14 UTC, quochieu586 commented on src/controllers/maze.controller.ts
> +    async singleMove(req: Request, res: Response) {
Dạ ròi

2023-08-19 05:14 UTC, quochieu586 commented on src/controllers/maze.controller.ts
> +            var result: any;
Dạ ròi

2023-08-19 05:15 UTC, quochieu586 commented on src/controllers/maze.controller.ts
> +            switch (req.query.move) {
Dạ ròi

2023-08-19 05:15 UTC, quochieu586 commented on src/models/maze_game.model.ts
> +// export enum CellType {
Dạ ròi

2023-08-19 05:15 UTC, quochieu586 commented on src/controllers/maze.controller.ts
> +                case 'w':
Chỗ này e đưa qua service ròi switch cases thành enum của cái Direction luôn á a

2023-08-19 05:16 UTC, quochieu586 commented on src/models/maze_game.model.ts
> +export interface CellObject {
Dạ để chỉ mấy thuộc tính của Cell á anh, nó là cái key để mình lưu trên db với xử lí mấy cái logic trong be luôn :v

2023-08-19 05:16 UTC, quochieu586 commented on src/models/maze_game.model.ts
> +    index: number;
Dạ e xóa ròi ạ

2023-08-19 05:16 UTC, quochieu586 commented on src/models/maze_game_session.model.ts
> +export type MazeGameSessionDocument = Document & {
Dạ ròi :3

2023-08-19 05:16 UTC, quochieu586 commented on src/services/maze.service.ts
> +type Direction = 'up' | 'down' | 'left' | 'right';
Dạ ròi

2023-08-19 05:16 UTC, quochieu586 commented on src/services/maze.service.ts
> +            nextPosition = character.position + session.size.width;
Dạ e fix ròi ạ :3

2023-08-19 05:17 UTC, quochieu586 commented on src/services/maze.service.ts
> +    }
Dạ ròi a

2023-08-19 09:09 UTC, lygioian submitted a review, later dismissed

2023-08-19 09:33 UTC, lygioian submitted a review, later dismissed

2023-08-19 10:06 UTC, tomgermanyyyy submitted a review, later dismissed

2023-08-19 10:40 UTC, lygioian approved these changes

2023-08-19 10:43 UTC, merged