feat: api for multiple move maze
gdsc-hcmut/game-be pull request #72
Opened 2023-08-21 06:08 UTC by quochieu586

- add api for multiple move maze
- fix api for single move maze
- close #71

2023-08-26 10:41 UTC, tomgermanyyyy requested changes

2023-08-26 10:41 UTC, tomgermanyyyy commented on src/services/maze.service.ts
> +            session.moves = [...session.moves, move];
cái session.moves... bị trùng, đem ra ngoài switch case đi em

2023-08-26 10:41 UTC, tomgermanyyyy commented on src/services/maze.service.ts
> +    map: CellObject[];
```suggestion
    map: Cell[];
```
sửa lại tên cho anh nha

2023-08-26 10:41 UTC, tomgermanyyyy commented on src/services/maze.service.ts
> +function handleMultipleMove(
```suggestion
function handleMultipleMoves(

```

2023-08-26 10:41 UTC, tomgermanyyyy commented on src/services/maze.service.ts
> +            default:
tách hàm

2023-08-26 10:41 UTC, tomgermanyyyy commented on src/services/maze.service.ts
> +            session.moves = [...session.moves, move];
```suggestion
            session.moves = [...session.moves, move as Direction];

```

2023-08-26 10:41 UTC, tomgermanyyyy commented on src/services/maze.service.ts
> +        // }
ko xài xoá đi em

2023-09-03 05:24 UTC, quochieu586 commented on src/services/maze.service.ts
> +        // }
Dạ ròi

2023-09-03 05:24 UTC, quochieu586 commented on src/services/maze.service.ts
> +            session.moves = [...session.moves, move];
Dạ ròi

2023-09-03 05:32 UTC, quochieu586 commented on src/services/maze.service.ts
> +function handleMultipleMove(
Dạ ròi

2023-09-03 05:37 UTC, quochieu586 commented on src/services/maze.service.ts
> +            default:
phần này thì em thấy tách hàm ra rồi truyền logic hơi phức tạp, với lại phần này cũng không xài chung single với multiple moves được nên em tính để vậy luôn.

2023-09-03 06:01 UTC, tomgermanyyyy approved these changes

2023-09-03 07:26 UTC, closed without merging