Feat/73 maze chapter
gdsc-hcmut/game-be pull request #77
Opened 2023-08-26 10:35 UTC by quochieu586

- add
1. Maze chapter, chapter session model
2. Maze chapter, chapter session controller
3. Maze chapter, chapter session service
- New api (view in google sheet)
- close #73

2023-08-26 11:40 UTC, tomgermanyyyy requested changes

2023-08-26 11:40 UTC, tomgermanyyyy commented on src/controllers/maze_chapter_session.controller.ts
> +    async startSession(req: Request, res: Response) {
```suggestion
    async createNewMazeSession(req: Request, res: Response) {

```

2023-08-26 11:40 UTC, tomgermanyyyy commented on src/controllers/maze_chapter_session.controller.ts
> +    async getSession(req: Request, res: Response) {
```suggestion
    async getChapterSession(req: Request, res: Response) {

```

2023-08-26 11:40 UTC, tomgermanyyyy commented on src/controllers/maze_session.controller.ts
> +        this.router.post('/:id/moves', this.submitMultipleMove.bind(this));
```suggestion
        this.router.post('/:id/moves', this.submitMultipleMoves.bind(this));

```

2023-08-26 11:40 UTC, tomgermanyyyy commented on src/controllers/maze_session.controller.ts
> +            const session = await this.mazeService.startSession(userId, 1);
```suggestion
            const session = await this.mazeService.createSession(userId, 1);

```

2023-08-26 11:40 UTC, tomgermanyyyy commented on src/controllers/maze_session.controller.ts
> +            const useHelp: boolean = req.body.isEnableAnimation;
```suggestion
            const canUseHelp: boolean = req.body.isEnableAnimation;

```

2023-08-26 11:40 UTC, tomgermanyyyy commented on src/services/maze.service.ts
> +        //         moveDirection = Direction.Right;
xoa comment

2023-08-26 11:40 UTC, tomgermanyyyy commented on src/services/maze_chapter_session.service.ts
> +        var isNewChapter = false;
no var

2023-08-26 14:37 UTC, quochieu586 commented on src/controllers/maze_chapter_session.controller.ts
> +        this.router.post('/:id/start', this.startSession.bind(this));
Dạ ròi

2023-08-26 14:37 UTC, quochieu586 commented on src/controllers/maze_chapter_session.controller.ts
> +    async startSession(req: Request, res: Response) {
Dạ ròi :3

2023-08-26 14:38 UTC, quochieu586 commented on src/controllers/maze_chapter_session.controller.ts
> +    async getSession(req: Request, res: Response) {
Dạ ròi

2023-08-26 14:46 UTC, quochieu586 commented on src/controllers/maze_session.controller.ts
> +            const session = await this.mazeService.startSession(userId, 1);
Dạ ròi

2023-08-26 14:47 UTC, quochieu586 commented on src/controllers/maze_session.controller.ts
> +            const useHelp: boolean = req.body.isEnableAnimation;
Dạ ròi

2023-08-26 14:49 UTC, quochieu586 commented on src/services/maze.service.ts
> +        //         moveDirection = Direction.Right;
Dạ ròi :3

2023-08-26 14:53 UTC, quochieu586 commented on src/services/maze_chapter_session.service.ts
> +        var isNewChapter = false;
Dạ ròi

2023-09-03 05:21 UTC, quochieu586 commented on src/controllers/maze_session.controller.ts
> +        this.router.post('/:id/moves', this.submitMultipleMove.bind(this));
Dạ ròi

2023-09-03 05:56 UTC, adminfessior submitted a review, later dismissed

2023-09-03 05:57 UTC, tomgermanyyyy submitted a review, later dismissed

2023-09-03 07:20 UTC, tomgermanyyyy approved these changes

2023-09-03 07:24 UTC, tomgermanyyyy approved these changes

2023-09-03 07:26 UTC, merged